### ISSUE TITLE
Customer is unable to manage/login to the Pure1 Collector via PowerShell - case 00805420 

### ISSUE THREAD

**Issue by cmilder** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#25] opened 2020-07-21 10:30 UTC
Below is the customer's description of the issue, any help is highly appreciated:

Hello - we're running into difficulties managing our Pure1 Collector appliances with Powershell. We're getting the following Powershell error when attempting to connect to an appliance:
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.Software\1.3.0.0\PureStorage.FlashArray.VMware.Software.psm1:1339 char:29
+ if ($queryResponse.("P$($i)").GetType().Name -eq "Byte")
+ ~~
+ CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvokeMethodOnNull

When the same connection is attempted, and we purposely supply incorrect credentials, a different error is received:
Invalid credentials for VM gk2-pure1collector
At C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.Software\1.3.0.0\PureStorage.FlashArray.VMware.Software.psm1:1079 char:11
+ throw "Invalid credentials for VM $($vm.name)"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (Invalid credent...-pure1collector:String) [], RuntimeException
+ FullyQualifiedErrorId : Invalid credentials for VM gk2-pure1collector

The two different errors tell us that authentication is authorized when the correct credential are supplied, but that something is preventing connection to manage the appliance.

**Comment by codyhosterman** [comment] 2020-07-21 15:01
What command are they running?

**Comment by codyhosterman** [comment] 2020-07-21 15:13
Also they seem to be on an old version--looks like 1.3.0.0, the latest version is 1.5.0.0. Run update-module PureStorage.FlashArray.VMware and try again. I ran this in my lab end to end and it works, so let's make sure first it isnt some already fixed bug.

**Comment by cmilder** [comment] 2020-07-24 03:33
Hey Cody,

Thanks for getting back to me.

Let me ask what commands they were running. Today is my day off but he sent me an additional email with more info.

Here is what he sent:

`Hi - not sure if this is directly relevant, but it does appear to be a problem on one of our two collectors (gk2-pure1collector).

One of the three vcenters configured in this collector seems to be unable to complete a collection cycle. Here's some evidence:

pureuser@purestorage-vma-collector:~$ purevmanalytics list
Name Enabled State Duration (s) Last collection
--------------------------- --------- ---------- -------------- -------------------------
gk2-vcmgmt-02.ddscloud.com True IDLE 171.025 2020-07-19 13:08:16+00:00
VCENTER3.ddscloud.com True COLLECTING 743.512 2020-06-06 10:06:43+00:00
gk2-vcenter-01.ddscloud.com True IDLE 188.572 2020-07-19 13:08:33+00:00

pureuser@purestorage-vma-collector:~$ purevmanalytics list
Name Enabled State Duration (s) Last collection
--------------------------- --------- ---------- -------------- -------------------------
gk2-vcmgmt-02.ddscloud.com True COLLECTING 178.087 2020-07-19 14:18:27+00:00
VCENTER3.ddscloud.com True COLLECTING 743.512 2020-06-06 10:06:43+00:00
gk2-vcenter-01.ddscloud.com True COLLECTING 195.293 2020-07-19 14:18:44+00:00

pureuser@purestorage-vma-collector:~$ purevmanalytics list
Name Enabled State Duration (s) Last collection
--------------------------- --------- ---------- -------------- -------------------------
gk2-vcmgmt-02.ddscloud.com True IDLE 171.642 2020-07-19 17:48:27+00:00
VCENTER3.ddscloud.com True COLLECTING 743.512 2020-06-06 10:06:43+00:00
gk2-vcenter-01.ddscloud.com True IDLE 189.588 2020-07-19 17:48:45+00:00

pureuser@purestorage-vma-collector:~$ purevmanalytics list
Name Enabled State Duration (s) Last collection
--------------------------- --------- ---------- -------------- -------------------------
gk2-vcmgmt-02.ddscloud.com True IDLE 179.653 2020-07-19 17:58:36+00:00
VCENTER3.ddscloud.com True COLLECTING 743.512 2020-06-06 10:06:43+00:00
gk2-vcenter-01.ddscloud.com True IDLE 197.286 2020-07-19 17:58:53+00:00

pureuser@purestorage-vma-collector:~$ purevmanalytics list
Name Enabled State Duration (s) Last collection
--------------------------- --------- ---------- -------------- -------------------------
gk2-vcmgmt-02.ddscloud.com True IDLE 174.469 2020-07-23 18:42:43+00:00
VCENTER3.ddscloud.com True COLLECTING 743.512 2020-06-06 10:06:43+00:00
gk2-vcenter-01.ddscloud.com True IDLE 196.381 2020-07-23 18:43:05+00:00`

**Comment by cmilder** [comment] 2020-07-25 04:25
Customer has gotten back to me. 

Regarding the module version question:

 

I’ve run the specifiedcommand: update-module PureStorage.FlashArray.VMware.
Here’s the fresh output from running Get-Module (filtered to only show PureStorage components):
 

PS C:\Users\cross9k\OneDrive - terago.ca\Documents\PowerShell> get-module

 

ModuleType Version    Name                                ExportedCommands                                                                                                              

---------- -------    ----                                ----------------                                                                                                             

Manifest   1.4.1.1    PureStorage.FlashArray.VMware                                                                                                                                    

Script     1.5.0.1    PureStorage.FlashArray.VMware.Co... {Get-PfaConnectionFromArrayId, Get-PfaConnectionOfDatastore, Get-PfaDatastore, Get-PfaHostFromVmHost...}                     

Script     1.0.0.1    PureStorage.FlashArray.VMware.Pure1 {get-leastBusyPfaConnection, new-pfaConnectionsWithPureOne}                                                                   

Script     1.1.0.1    PureStorage.FlashArray.VMware.RDM   {Convert-PfaRDMToVvol, Copy-PfaSnapshotToRDM, Get-PfaConnectionFromRDM, Get-PfaRDMSnapshot...}                               

Script     1.5.0.0    PureStorage.FlashArray.VMware.So... {Deploy-PfaAppliance, Get-PfaAppliance, Get-PfavSpherePlugin, Install-PfavSpherePlugin...}                                   

Script     1.1.0.2    PureStorage.FlashArray.VMware.VMFS  {Add-PfaVmfsToCluster, Get-PfaVmfsSnapshot, Get-PfaVMFSVol, New-PfaVmfs...}                                                   

Script     1.4.0.1    PureStorage.FlashArray.VMware.vVol  {Add-KeyManagementServer, Add-VsanObjectToRepairQueue, Copy-VDisk, Export-SpbmStoragePolicy...}                              

Script     1.0.0.1    PureStorage.Pure1                   {Get-PureOneArray, Get-PureOneArrayBusyMeter, Get-PureOneArrayNetworking, Get-PureOneArrayTag...}                            

Binary     1.17.3.0   PureStoragePowerShellSDK            {Add-PfaArrayToPod, Add-PfaHostGroupsToProtectionGroup, Add-PfaHostIqns, Add-PfaHostNqn...}               

 

**After running the update-module command, the same errors are returned when running these commands:**

 

connect-viserver gk2-vcmgmt-02.ddscloud.com

$creds = get-credential

$ova = Get-PfaAppliance -vm (get-vm gk2-pure1collector) -applianceCredentials $creds

 

Name                           Port  User                         

----                           ----  ----                         

gk2-vcmgmt-02.ddscloud.com     443   DDSCLOUD.COM\cross           

cmdlet Get-Credential at command pipeline position 1

Supply values for the following parameters:

You cannot call a method on a null-valued expression.

At C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.Software\1.5.0.0\PureStorage.FlashArray.VMware.Software.psm1:1208 char:29

+     if ($queryResponse.("P$($i)").GetType().Name -eq "Byte")

+                             ~~

    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException

    + FullyQualifiedErrorId : InvokeMethodOnNull

 

**As noted before, a different error is returned if I specify an incorrect password for the PfaAppliance:**
 

Name                           Port  User                         

----                           ----  ----                         

gk2-vcmgmt-02.ddscloud.com     443   DDSCLOUD.COM\cross           

cmdlet Get-Credential at command pipeline position 1

Supply values for the following parameters:

Invalid credentials for VM gk2-pure1collector

At C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.Software\1.5.0.0\PureStorage.FlashArray.VMware.Software.psm1:911 char:11

+           throw "Invalid credentials for VM $($vm.name)"

+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : OperationStopped: (Invalid credent...-pure1collector:String) [], RuntimeException

    + FullyQualifiedErrorId : Invalid credentials for VM gk2-pure1collector

 

**Summary: the errors we’re seeing are unchanged after running the update-module PureStorage.FlashArray.VMware command.**


**The same Powershell commands are working as expected when run against our other Pure1 Collector appliance:**

<img width="596" alt="Screen Shot 2020-07-24 at 10 25 08 PM" src="https://user-images.githubusercontent.com/68592002/88448581-8e3c7180-cdfc-11ea-8a89-6247335e4260.png">

**Comment by swankier-pure** [comment] 2020-07-27 14:54
Hello Cody, I have taken over the case for Ceasar. Let me know if you need any additional information

**Comment by codyhosterman** [comment] 2020-08-20 20:20
So the issue was that the property count was higher than it actually was (i think there is some hidden metadata) so the loop went too long and tried to pull from null properties. I add a check for a null property so it will end the loop if that happens. This seems to fix the issue, i could reproduce it and when i made the change I no longer saw the issue. Will be in the next release.

**Closed by codyhosterman** 2020-08-20 20:20 UTC
Labels: bug, question
